### PR TITLE
Escape response for preventing XSS

### PR DESCRIPTION
**Pull request by nakaly**
Escape ">", "<" , "/", "+" in response.

### CODE REVIEW

**Comment by tokuhirom** [comment]
Would you add a test case?

**Comment by moznion** [comment]
I feel the class named `CustomCharacterEscapes` is a bit obscurity...
How about including `XSS` word in the class name?

**Comment by nakaly** [comment]
@moznion 
I just want to have a room for adding other escape characters although I do not have any plans...
How do you think it?

@tokuhirom  
I will add a test case!

**Comment by moznion** [comment]
:+1:

**Pull request merged**
